"""Technical findings report -- written for a SOC/IR analyst audience.

Full detail: every finding, technique mapping, IOC, the orchestrator's
decision trail (which tool ran and why), and drafted detection rules.
"""

from __future__ import annotations

from typing import Any

from aria.attck.mitre_mapping import lookup
from aria.reports.common import severity_counts, sorted_findings, timeline, unique_iocs


def render(state: dict[str, Any]) -> str:
    findings = sorted_findings(state)
    counts = severity_counts(state)

    lines: list[str] = []
    lines.append(f"# Technical Findings Report -- {state.get('case_name', 'Untitled Case')}")
    lines.append("")
    lines.append(f"**Case ID:** {state.get('case_id')}  ")
    lines.append(f"**Analyst of record:** {state.get('analyst')}  ")
    lines.append(f"**Case opened:** {state.get('started_at')}  ")
    lines.append(f"**Artifacts analyzed:** {', '.join(a['kind'] for a in state.get('artifacts', []))}")
    lines.append("")

    lines.append("## 1. Severity Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for sev in ("critical", "high", "medium", "low", "info"):
        lines.append(f"| {sev} | {counts.get(sev, 0)} |")
    lines.append("")

    lines.append("## 2. Orchestration Trail")
    lines.append("")
    lines.append(
        "ARIA is agent-orchestrated: each tool below ran because the prior tool's findings warranted it, "
        "not because of a fixed pipeline order."
    )
    lines.append("")
    lines.append("| # | Tool | Reason invoked | Findings produced |")
    lines.append("|---|---|---|---|")
    for i, run in enumerate(state.get("tool_runs", []), start=1):
        lines.append(f"| {i} | {run['tool']} | {run.get('reason', '')} | {run.get('finding_count', 0)} |")
    lines.append("")
    lines.append("<details><summary>Full orchestrator decision log</summary>\n")
    for entry in state.get("decision_log", []):
        lines.append(f"- {entry}")
    lines.append("\n</details>")
    lines.append("")

    lines.append("## 3. Detailed Findings")
    lines.append("")
    for f in findings:
        techs = ", ".join(f"`{t}` ({lookup(t)['name']})" for t in f.get("attack_techniques", []))
        lines.append(f"### [{f.get('severity', 'info').upper()}] {f.get('title')}")
        lines.append("")
        lines.append(f"- **Source tool:** {f.get('source_tool')}")
        lines.append(f"- **Confidence:** {f.get('confidence')}")
        if f.get("timestamp"):
            lines.append(f"- **Timestamp:** {f.get('timestamp')}")
        if techs:
            lines.append(f"- **ATT&CK techniques:** {techs}")
        if f.get("iocs"):
            lines.append(f"- **IOCs:** {', '.join(i for i in f['iocs'] if i)}")
        if f.get("evidence_refs"):
            lines.append(f"- **Evidence refs:** {', '.join(f['evidence_refs'])}")
        lines.append(f"- **Finding ID:** `{f.get('id')}`")
        lines.append("")
        lines.append(f"{f.get('description')}")
        lines.append("")

    tl = timeline(state)
    if tl:
        lines.append("## 4. Incident Timeline")
        lines.append("")
        lines.append("| Timestamp (UTC) | Event | Source |")
        lines.append("|---|---|---|")
        for f in tl:
            lines.append(f"| {f['timestamp']} | {f.get('title')} | {f.get('source_tool')} |")
        lines.append("")

    iocs = unique_iocs(state)
    if iocs:
        lines.append("## 5. Indicators of Compromise")
        lines.append("")
        for ioc in iocs:
            lines.append(f"- `{ioc}`")
        lines.append("")

    rules = state.get("detection_rules", [])
    if rules:
        lines.append("## 6. Drafted Detection Rules (Sigma-style)")
        lines.append("")
        lines.append(
            "Generated by the AI Detection Engineer node based on this incident's confirmed techniques. "
            "Review and tune thresholds before deploying to production."
        )
        lines.append("")
        for rule in rules:
            lines.append(f"### {rule['title']}  \n`{rule['id']}` -- level: **{rule['level']}**")
            lines.append("")
            lines.append("```yaml")
            lines.append(f"title: {rule['title']}")
            lines.append(f"id: {rule['id']}")
            lines.append(f"level: {rule['level']}")
            lines.append(f"logsource: {rule['logsource']}")
            lines.append(f"detection: {rule['detection']}")
            lines.append(f"tags: {rule['attack_techniques']}")
            lines.append("```")
            lines.append("")

    lines.append("## 7. ATT&CK Coverage")
    lines.append("")
    lines.append("See `attck_heatmap.html` and `attck_navigator_layer.json` in this report package.")
    lines.append("")
    for tech_id, count in sorted(state.get("attack_techniques", {}).items(), key=lambda t: -t[1]):
        meta = lookup(tech_id)
        lines.append(f"- `{tech_id}` -- {meta['name']} ({meta['tactic']}) -- observed {count}x")

    return "\n".join(lines)
