"""ATT&CK technique heatmap generation.

Produces two artifacts from `state["attack_techniques"]` (technique_id ->
occurrence count, accumulated across every tool in the graph):

1. A MITRE ATT&CK Navigator-compatible layer JSON (`layer.json`) -- drop it
   straight into https://mitre-attack.github.io/attack-navigator/ or a local
   Navigator instance for an interactive, industry-standard view.
2. A self-contained standalone HTML heatmap (no external dependencies) for
   quick viewing without a Navigator instance -- this is what gets embedded
   in the technical report.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from aria.attck.mitre_mapping import TACTIC_ORDER, lookup

_COLOR_STOPS = [
    (0, "#f2f4f7"),
    (1, "#ffe3b3"),
    (2, "#ffb454"),
    (3, "#ff7a45"),
    (5, "#e0342b"),
    (999, "#8b0000"),
]


def _color_for_count(count: int) -> str:
    color = _COLOR_STOPS[0][1]
    for threshold, c in _COLOR_STOPS:
        if count >= threshold:
            color = c
    return color


def build_navigator_layer(state: dict[str, Any]) -> dict[str, Any]:
    techniques = state.get("attack_techniques", {})
    max_count = max(techniques.values(), default=1)

    layer = {
        "name": f"ARIA - {state.get('case_name', 'Incident')}",
        "versions": {"attack": "15", "navigator": "4.9.1", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": f"Auto-generated by ARIA for case {state.get('case_id', '')}. "
        f"{len(techniques)} unique technique(s) observed across {len(state.get('tool_runs', []))} tool run(s).",
        "techniques": [
            {
                "techniqueID": tech_id,
                "score": count,
                "color": _color_for_count(count),
                "comment": f"Observed {count}x. {lookup(tech_id)['name']}",
                "enabled": True,
            }
            for tech_id, count in techniques.items()
        ],
        "gradient": {
            "colors": ["#f2f4f7", "#ffe3b3", "#ff7a45", "#8b0000"],
            "minValue": 0,
            "maxValue": max_count,
        },
        "legendItems": [
            {"label": "Not observed", "color": "#f2f4f7"},
            {"label": "Observed once", "color": "#ffe3b3"},
            {"label": "Observed 2-4x", "color": "#ff7a45"},
            {"label": "Observed 5+ / core to incident", "color": "#8b0000"},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }
    return layer


def _grouped_by_tactic(state: dict[str, Any]) -> dict[str, list[tuple[str, str, int]]]:
    techniques = state.get("attack_techniques", {})
    grouped: dict[str, list[tuple[str, str, int]]] = {t: [] for t in TACTIC_ORDER}
    grouped.setdefault("unknown", [])
    for tech_id, count in techniques.items():
        meta = lookup(tech_id)
        grouped.setdefault(meta["tactic"], []).append((tech_id, meta["name"], count))
    return {k: v for k, v in grouped.items() if v}


def build_html_heatmap(state: dict[str, Any]) -> str:
    grouped = _grouped_by_tactic(state)

    columns = []
    for tactic, techs in grouped.items():
        rows = "".join(
            f'<div class="cell" style="background:{_color_for_count(count)}" '
            f'title="{name} -- observed {count}x">'
            f'<span class="tid">{tech_id}</span><span class="tname">{name}</span>'
            f'<span class="count">x{count}</span></div>'
            for tech_id, name, count in sorted(techs, key=lambda t: -t[2])
        )
        columns.append(
            f'<div class="tactic-col"><div class="tactic-header">{tactic.replace("-", " ").title()}</div>{rows}</div>'
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ARIA ATT&amp;CK Heatmap -- {state.get('case_name', '')}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Helvetica, Arial, sans-serif; background:#0d1117; color:#e6edf3; margin:0; padding:24px; }}
  h1 {{ font-size: 20px; margin: 0 0 4px 0; }}
  .meta {{ color:#8b949e; font-size:13px; margin-bottom:20px; }}
  .board {{ display:flex; gap:10px; overflow-x:auto; align-items:flex-start; }}
  .tactic-col {{ min-width:190px; background:#161b22; border-radius:8px; padding:8px; }}
  .tactic-header {{ font-size:12px; font-weight:600; text-transform:uppercase; letter-spacing:.04em; color:#c9d1d9; padding:6px 4px 10px 4px; border-bottom:1px solid #30363d; margin-bottom:6px; }}
  .cell {{ border-radius:5px; padding:8px; margin-bottom:6px; color:#111; font-size:12px; line-height:1.35; cursor:default; }}
  .tid {{ display:block; font-weight:700; }}
  .tname {{ display:block; font-weight:500; }}
  .count {{ display:block; font-size:11px; opacity:.75; margin-top:2px; }}
  .legend {{ display:flex; gap:14px; margin-top:20px; font-size:12px; color:#8b949e; align-items:center; }}
  .swatch {{ width:14px; height:14px; border-radius:3px; display:inline-block; margin-right:6px; vertical-align:middle; }}
</style>
</head>
<body>
  <h1>ATT&amp;CK Technique Heatmap</h1>
  <div class="meta">Case: {state.get('case_name', '')} ({state.get('case_id', '')}) &middot;
  {len(state.get('attack_techniques', {}))} unique technique(s) across
  {len(state.get('tool_runs', []))} tool run(s)</div>
  <div class="board">
    {''.join(columns)}
  </div>
  <div class="legend">
    <span><span class="swatch" style="background:#ffe3b3"></span>Observed once</span>
    <span><span class="swatch" style="background:#ff7a45"></span>Observed 2-4x</span>
    <span><span class="swatch" style="background:#8b0000"></span>Observed 5+ / core to incident</span>
  </div>
</body>
</html>"""


def write_heatmap_artifacts(state: dict[str, Any], output_dir: str) -> tuple[str, str]:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    layer_path = out / "attck_navigator_layer.json"
    layer_path.write_text(json.dumps(build_navigator_layer(state), indent=2), encoding="utf-8")

    html_path = out / "attck_heatmap.html"
    html_path.write_text(build_html_heatmap(state), encoding="utf-8")

    return str(layer_path), str(html_path)
